{% set name = "rocket-fft" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/styfenschaer/rocket-fft/archive/v{{ version }}.tar.gz
  sha256: f69e7af02960e815f331129d03d5efdd5c47fc1ecbe4d3f4bb68756a3b6b1003

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numba >=0.56.0
    - numpy
    - pip
    - python
    - setuptools >=59.2.0
  run:
    - numba >=0.56.0
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - rocket_fft
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rocket-fft
  summary: Rocket-FFT extends Numba by scipy.fft and numpy.fft
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/styfenschaer/rocket-fft

extra:
  recipe-maintainers:
    - goanpeca
